name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  
    - name: Deploy to Docker
      uses: tvrcgo/docker-builder@v0.3.1
      with:
         registry: docker.io
         username: gho7004230
         password: dckr_pat_f0J5ifSuRfZL7Fo2JgiXVeb2Phg
         repository: gho7004230/python
         tag: latest
